ARG PHP_VERSION

FROM php:${PHP_VERSION}-fpm-alpine as prod

COPY configure.sh /
COPY www.conf /usr/local/etc/php-fpm.d/www.conf
COPY php.ini /usr/local/etc/php/conf.d
RUN /configure.sh \
    && rm /configure.sh
WORKDIR /var/www

FROM prod as dev
ARG FPM_UID
RUN apk add --no-cache $PHPIZE_DEPS shadow\
        && usermod -u ${FPM_UID} www-data \
        && pecl install xdebug \
        && docker-php-ext-enable xdebug \
        && apk del $PHPIZE_DEPS shadow