name: deploy to ghcr.io
on:
  push:
    branches: [ master ]

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BASE_IMAGE_NAME: php7.1-suzukifr
      PHP_VERSION: 7.1
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build and push prod-php-fpm
        uses: docker/build-push-action@v2
        with:
          context: ./
          build-args: |
            PHP_VERSION=${{ env.PHP_VERSION }}
          file: ./Dockerfile-fpm
          push: true
          cache-from: type=registry,ref=${{ github.repository_owner }}/prod-${{ env.BASE_IMAGE_NAME }}-fpm:latest
          cache-to: type=inline
          tags: ghcr.io/${{ github.repository_owner }}/prod-${{ env.BASE_IMAGE_NAME }}-fpm:latest
          target: prod
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      - name: Build and push dev-php-fpm
        uses: docker/build-push-action@v2
        with:
          context: ./
          build-args: |
            PHP_VERSION=${{ env.PHP_VERSION }}
          file: ./Dockerfile-fpm
          push: true
          cache-from: type=registry,ref=${{ github.repository_owner }}/dev-${{ env.BASE_IMAGE_NAME }}-fpm:latest
          cache-to: type=inline
          tags: ghcr.io/${{ github.repository_owner }}/dev-${{ env.BASE_IMAGE_NAME }}-fpm:latest
          target: dev
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          build-args: |
            PHP_VERSION=${{ env.PHP_VERSION }}
          file: ./Dockerfile-build
          push: true
          cache-from: type=registry,ref=${{ github.repository_owner }}/build-${{ env.BASE_IMAGE_NAME }}:latest
          cache-to: type=inline
          tags: ghcr.io/${{ github.repository_owner }}/build-${{ env.BASE_IMAGE_NAME }}:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
